# Generated by Django 4.2.6 on 2024-10-19 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TechStackTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='WorkConditionTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('work_format', models.CharField(choices=[('remote', 'Удаленная'), ('hybrid', 'Гибридная'), ('onsite', 'Очная')], default='onsite', max_length=10)),
                ('min_salary', models.PositiveIntegerField()),
                ('max_salary', models.PositiveIntegerField()),
                ('currency', models.CharField(choices=[('RUB', 'RUB'), ('USD', 'USD'), ('EUR', 'EUR')], default='RUB', max_length=3)),
                ('experience', models.CharField(choices=[('0', 'Без опыта'), ('1', 'До 1 года'), ('1-3', 'от 1 до 3 лет'), ('3-6', 'от 3 до 6 лет'), ('6', 'более 6 лет')], default='<1', max_length=10)),
                ('city', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('number_of_openings', models.PositiveIntegerField()),
                ('description', models.TextField()),
                ('work_condition_tags', models.CharField(choices=[('full_time', 'Полная ставка'), ('part_time', 'Неполная ставка'), ('internship', 'Стажировка'), ('volunteering', 'Волонтерство'), ('one_time', 'Разовое задание'), ('project', 'Проектная работа')], default='full_time', max_length=20)),
                ('publication_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('published', 'Опубликована'), ('archived', 'В архиве'), ('checking', 'На проверке')], default='published', max_length=10)),
                ('tech_stack_tags', models.ManyToManyField(blank=True, to='api.techstacktag')),
            ],
        ),
    ]
