# Generated by Django 5.1.2 on 2024-10-18 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WorkConditionTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('min_salary', models.PositiveIntegerField()),
                ('max_salary', models.PositiveIntegerField()),
                ('currency', models.CharField(choices=[('RUB', 'RUB'), ('USD', 'USD'), ('EUR', 'EUR')], default='RUB', max_length=3)),
                ('city', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('number_of_openings', models.PositiveIntegerField()),
                ('description', models.TextField()),
                ('tech_stack_tags', models.CharField(max_length=255)),
                ('publication_date', models.DateField(auto_now_add=True)),
                ('work_condition_tags', models.ManyToManyField(to='api.workconditiontag')),
            ],
        ),
    ]
