# Generated by Django 5.1.2 on 2024-10-18 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TechStackTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='vacancy',
            name='tech_stack_tags',
        ),
        migrations.AddField(
            model_name='vacancy',
            name='tech_stack_tags',
            field=models.ManyToManyField(blank=True, to='api.techstacktag'),
        ),
    ]
