# Generated by Django 4.2.6 on 2024-10-29 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='techstacktag',
            options={'verbose_name': 'Технология', 'verbose_name_plural': 'Технологии'},
        ),
        migrations.AlterModelOptions(
            name='vacancy',
            options={'verbose_name': 'Вакансия', 'verbose_name_plural': 'Вакансии'},
        ),
        migrations.AlterModelOptions(
            name='workconditiontag',
            options={'verbose_name': 'Условие работы', 'verbose_name_plural': 'Условия работы'},
        ),
        migrations.AlterField(
            model_name='techstacktag',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Технология'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='address',
            field=models.CharField(max_length=255, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='city',
            field=models.CharField(max_length=255, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='currency',
            field=models.CharField(choices=[('RUB', 'RUB'), ('USD', 'USD'), ('EUR', 'EUR')], default='RUB', max_length=3, verbose_name='Валюта'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='experience',
            field=models.CharField(choices=[('0', 'Без опыта'), ('1', 'До 1 года'), ('1-3', 'от 1 до 3 лет'), ('3-6', 'от 3 до 6 лет'), ('6', 'более 6 лет')], default='0', max_length=10, verbose_name='Опыт работы'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='max_salary',
            field=models.PositiveIntegerField(verbose_name='Максимальная зарплата'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='min_salary',
            field=models.PositiveIntegerField(verbose_name='Минимальная зарплата'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='number_of_openings',
            field=models.PositiveIntegerField(verbose_name='Количество мест'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='publication_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='status',
            field=models.CharField(choices=[('published', 'Опубликована'), ('archived', 'В архиве'), ('checking', 'На проверке')], default='published', max_length=10, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='tech_stack_tags',
            field=models.ManyToManyField(blank=True, to='api.techstacktag', verbose_name='Технологии'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='work_condition_tags',
            field=models.CharField(choices=[('full_time', 'Полная ставка'), ('part_time', 'Неполная ставка'), ('internship', 'Стажировка'), ('volunteering', 'Волонтерство'), ('one_time', 'Разовое задание'), ('project', 'Проектная работа')], default='full_time', max_length=20, verbose_name='Условие работы'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='work_format',
            field=models.CharField(choices=[('remote', 'Удаленная'), ('hybrid', 'Гибридная'), ('onsite', 'Очная')], default='onsite', max_length=10, verbose_name='Формат работы'),
        ),
        migrations.AlterField(
            model_name='workconditiontag',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Условие работы'),
        ),
    ]
