# Generated by Django 5.1.2 on 2024-10-18 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_techstacktag_remove_vacancy_tech_stack_tags_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='status',
            field=models.CharField(choices=[('published', 'Опубликована'), ('archived', 'В архиве')], default='published', max_length=10),
        ),
    ]
