# Generated by Django 4.2.6 on 2024-10-29 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_techstacktag_options_alter_vacancy_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='tech_stack_tags',
            field=models.ManyToManyField(blank=True, to='api.techstacktag', verbose_name='Навыки'),
        ),
    ]
