# Generated by Django 5.1.2 on 2024-10-18 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_vacancy_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='publication_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
