# Generated by Django 4.2.6 on 2024-11-03 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_resume_applicant_resume_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Заголовок резюме'),
        ),
    ]
