# Generated by Django 5.1.2 on 2024-10-18 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_vacancy_publication_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='work_format',
            field=models.CharField(choices=[('remote', 'Удаленная'), ('hybrid', 'Гибридная'), ('onsite', 'Очная')], default='onsite', max_length=10),
        ),
        migrations.RemoveField(
            model_name='vacancy',
            name='work_condition_tags',
        ),
        migrations.AddField(
            model_name='vacancy',
            name='work_condition_tags',
            field=models.CharField(choices=[('full_time', 'Полная ставка'), ('part_time', 'Неполная ставка'), ('internship', 'Стажировка'), ('volunteering', 'Волонтерство'), ('one_time', 'Разовое задание'), ('project', 'Проектная работа')], default='full_time', max_length=20),
        ),
    ]
