# Generated by Django 4.2.6 on 2024-10-18 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_vacancy_work_format_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='experience',
            field=models.CharField(choices=[('0', 'Без опыта'), ('1', 'До 1 года'), ('1-3', 'от 1 до 3 лет'), ('3-6', 'от 3 до 6 лет'), ('6', 'более 6 лет')], default='<1', max_length=10),
        ),
    ]
