# Generated by Django 4.2.6 on 2024-11-03 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_alter_resume_title"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="resume",
            name="title",
        ),
    ]
