# Generated by Django 4.2.6 on 2024-11-07 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0011_alter_resume_degree"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resume",
            name="degree",
            field=models.CharField(
                choices=[
                    ("speciality", "Специалитет"),
                    ("bachelor", "Бакалавриат"),
                    ("unfinished_higher", "Неоконченное высшее"),
                    ("vocational", "СПО"),
                    ("unfinished_secondary", "Неоконченное среднее"),
                ],
                max_length=100,
                verbose_name="Степень",
            ),
        ),
    ]
