# Generated by Django 4.2.6 on 2024-11-07 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_resume_specialization_alter_resume_degree_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vacancy',
            old_name='work_condition_tags',
            new_name='employment_type',
        ),
        migrations.RenameField(
            model_name='vacancy',
            old_name='work_format',
            new_name='format',
        ),
    ]
