# Generated by Django 5.1.3 on 2024-11-17 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0016_rename_skills_resume_tech_stack_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="techstacktag",
            name="name",
            field=models.CharField(
                max_length=100, unique=True, verbose_name="Название"
            ),
        ),
    ]
