# Generated by Django 5.1.3 on 2024-11-17 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0017_alter_techstacktag_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="resume",
            name="content",
            field=models.CharField(
                default="Test", max_length=255, verbose_name="Описание резюме"
            ),
            preserve_default=False,
        ),
    ]
