# Generated by Django 5.1.3 on 2024-11-19 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_vacancy_languages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='work_experience',
        ),
        migrations.AddField(
            model_name='resume',
            name='experience',
            field=models.CharField(choices=[('0', 'Без опыта'), ('1', 'До 1 года'), ('1-3', 'от 1 до 3 лет'), ('3-6', 'от 3 до 6 лет'), ('6', 'более 6 лет')], default='0', max_length=10, verbose_name='Опыт работы'),
        ),
    ]
