# Generated by Django 5.1.3 on 2024-11-26 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0021_rename_techstacktag_tag_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="WorkConditionTag",
        ),
    ]
