# Generated by Django 5.1.3 on 2025-01-07 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0022_delete_workconditiontag"),
    ]

    operations = [
        migrations.AlterField(
            model_name="language",
            name="name",
            field=models.CharField(max_length=50, unique=True, verbose_name="Язык"),
        ),
    ]
