# Generated by Django 4.2.6 on 2024-10-26 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_alter_customuser_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='CUSTOM_username',
        ),
    ]
