# Generated by Django 4.2.6 on 2024-10-31 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0004_applicant"),
    ]

    operations = [
        migrations.AlterField(
            model_name="applicant",
            name="company_name",
            field=models.CharField(max_length=255, verbose_name="Имя компании"),
        ),
    ]
