# Используем официальный образ Python как базовый
FROM python:3.12-slim

RUN apt-get update && apt-get install -y \
    build-essential \
    libpq-dev \
    && rm -rf /var/lib/apt/lists/*

# Устанавливаем рабочую директорию внутри контейнера
WORKDIR /app

# Копируем файлы requirements.txt в контейнер
COPY requirements.txt /app/

# Устанавливаем зависимости
RUN pip install --no-cache-dir -r requirements.txt

# Копируем весь проект в контейнер
COPY . /app/

# Собираем статические файлы Django
RUN python manage.py collectstatic --noinput

# Открываем порт, на котором будет работать приложение
EXPOSE 8000

# Запуск приложения Django
CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]
